<a href="https://colab.research.google.com/github/mscitpract/DL/blob/main/Addition_of_two_Vector%2C_Matrix_and_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# Addition of two vectors
V1 = np.array([1,2,3,4])
V2 = np.array([3,2,5,4])
Vector_addition = V1+V2
Vector_addition

array([4, 4, 8, 8])

In [3]:
# Addition of two matrix
M1 = np.array([[1,2],[3,4],[5,6],[7,8]])
M2 = np.array([[2,2],[4,4],[6,6],[7,8]])
Matrix_addition = M1+M2
Matrix_addition

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [14, 16]])

In [4]:
#Tensor Addition
T1 = tf.constant([[1,2],[3,4],[5,6],[7,8]])
T2 = tf.constant([[3,2],[5,4],[7,6],[9,8]])
Tensor_addition = T1+T2
Tensor_addition

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 4,  4],
       [ 8,  8],
       [12, 12],
       [16, 16]], dtype=int32)>