<a href="https://colab.research.google.com/github/mscitpract/DL/blob/main/Create_vector%2C_Matrix_and_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [5]:
V = np.array([1,2,3,4])
V

array([1, 2, 3, 4])

In [7]:
M = np.array([[1,2],[3,4],[5,6],[7,8]])
M

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
T = tf.constant([[1,2]], dtype=tf.int32)
T

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>