<a href="https://colab.research.google.com/github/mscitpract/DL/blob/main/DLP1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import tensorflow as tf

x=np.array([1,2,3,4])
print("Create a Vector: ",x)
print("\n")

A=np.array([[1,2],[3,4],[5,6]])
print("Create a Matrix: \n",A)
print("\n")

tensor_A=tf.constant([[1,2]],dtype=tf.int32)
print("Create a Tensor: ",tensor_A)
print("\n")


Create a Vector:  [1 2 3 4]


Create a Matrix: 
 [[1 2]
 [3 4]
 [5 6]]


Create a Tensor:  tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)




In [6]:
A=np.array([[1,2],[3,4],[5,6]])
print("A= ",A)
print("\n")

B=np.array([[2,5],[7,4],[4,3]])
print("B= ",B)
print("\n")

C=A*B
print("Multiplication of two Matrix: \n",C)
print("\n")

x=np.array([1,2,3,4])
y=np.array([5,6,7,8])

z=x*y
print("Multiplication of two Vector: ",z)
print("\n")

tensor_A=tf.constant([[4,2]],dtype=tf.int32)
print("A: ",tensor_A)

tensor_B=tf.constant([[7,4]],dtype=tf.int32)
print("B: ",tensor_B,"\n")

tensor_multiply=tf.multiply(tensor_A,tensor_B)
print("Multiplication of two Tensor: ",tensor_multiply)
print("\n")

x=np.array([1,2,3,4])
y=np.array([5,6,7,8])

z=x+y
print("Addition of two Matrix: ",z)
print("\n")

A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[2,5],[7,4],[4,3]])

C=A*B
print("Addition of two Vector: \n",C)
print("\n")

tensor_add=tf.add(tensor_A,tensor_B)
print("Addition of two Tensor: ",tensor_add)
print("\n")

A=  [[1 2]
 [3 4]
 [5 6]]


B=  [[2 5]
 [7 4]
 [4 3]]


Multiplication of two Matrix: 
 [[ 2 10]
 [21 16]
 [20 18]]


Multiplication of two Vector:  [ 5 12 21 32]


A:  tf.Tensor([[4 2]], shape=(1, 2), dtype=int32)
B:  tf.Tensor([[7 4]], shape=(1, 2), dtype=int32) 

Multiplication of two Tensor:  tf.Tensor([[28  8]], shape=(1, 2), dtype=int32)


Addition of two Matrix:  [ 6  8 10 12]


Addition of two Vector: 
 [[ 2 10]
 [21 16]
 [20 18]]


Addition of two Tensor:  tf.Tensor([[11  6]], shape=(1, 2), dtype=int32)




In [7]:
x=np.array([1,2,3,7,3,5,2])
y=np.array([[1],[3],[5],[7],[8],[8],[2]])
c=x*y
print("Multiplication of Vector and Matrix: \n",c)
print("\n")

U=[2,-3]
V=[1,3]
dotproduct=np.dot(U,V)
print("Matrix dot product: ",dotproduct)
print("\n")

A=np.array([[6,1,1],
            [4,-2,5],
            [2,8,7]])
print("Inverse of Matrix: \n",np.linalg.inv(A))
print("\n")

Multiplication of Vector and Matrix: 
 [[ 1  2  3  7  3  5  2]
 [ 3  6  9 21  9 15  6]
 [ 5 10 15 35 15 25 10]
 [ 7 14 21 49 21 35 14]
 [ 8 16 24 56 24 40 16]
 [ 8 16 24 56 24 40 16]
 [ 2  4  6 14  6 10  4]]


Matrix dot product:  -7


Inverse of Matrix: 
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


