<a href="https://colab.research.google.com/github/mscitpract/DL/blob/main/Multiplication_of_two_Vector%2C_Matrix_and_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [3]:
#multiplication of two Matrix
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[2,2],[4,4],[6,6],[7,8]])
C = A*B
C

array([[ 2,  4],
       [12, 16],
       [30, 36],
       [49, 64]])

In [4]:
#vector multiplication
V1 = np.array([1,2,3,4])
V2 = np.array([3,2,5,4])
Vector_multiplication = V1*V2
Vector_multiplication

array([ 3,  4, 15, 16])

In [5]:
#Tensor multiplication
T1 = tf.constant([[1,2],[3,4],[5,6],[7,8]])
T2 = tf.constant([[3,2],[5,4],[7,6],[9,8]])
Tensor_multiplication = T1*T2
Tensor_multiplication

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  4],
       [15, 16],
       [35, 36],
       [63, 64]], dtype=int32)>